config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^privacy/$', TemplateView.as_view(template_name='pages/privacy.html'), name="privacy"),

    # Django Admin (Comment the next line to disable the admin)
    url(r'^admin/', include(admin.site.urls)),

    # User management
    # url(r'^users/', include("fossevents.users.urls", namespace="users")),
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fossevents/events/urls.py
# Third Party Stuff
from django.conf.urls import url

from .views import EventCreateView, EventUpdateView, event_review

uuid_regex = '[a-fA-F0-9]{8}-?[a-fA-F0-9]{4}-?[1345][a-fA-F0-9]{3}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{12}'

app_name = 'events'
urlpatterns = [
    url(r'^add/$', EventCreateView.as_view(), name="create"),
    url(r'^update/(?P<slug>[-\w]+)-(?P<pk>%s)-(?P<token>%s)/$' % (uuid_regex, uuid_regex),
        EventUpdateView.as_view(), name="update"),
    url(r'^review/(?P<slug>[-\w]+)-(?P<pk>%s)-(?P<token>%s)/$' % (uuid_regex, uuid_regex),
        event_review, name="review"),
]

fossevents/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from .events.feeds import AtomLatestEventFeed, LatestEvents
from .events.views import event_detail
from .views import homepage

uuid_regex = '[a-fA-F0-9]{8}-?[a-fA-F0-9]{4}-?[1345][a-fA-F0-9]{3}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{12}'

urlpatterns = [
    url(r'^$', homepage, name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
    url(r'^privacy/$', TemplateView.as_view(template_name='privacy.html'), name="privacy"),
    url(r'^(?P<slug>[-\w]+)-(?P<pk>%s)/$' % uuid_regex, event_detail, name="event-detail"),
    url(r'^event/', include('fossevents.events.urls', namespace='events')),
    url(r'^users/', include('fossevents.users.urls', namespace='users')),
]

urlpatterns += [
    url(r'^feed/rss\.xml$', LatestEvents(), name='feed-rss'),
    url(r'^feed/atom\.xml$', AtomLatestEventFeed(), name='feed-atom'),
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^markdown/', include('django_markdown.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^devrecargar/', include(('devrecargar.urls', 'devrecargar'),
                        namespace='devrecargar'))]
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

fossevents/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import logout

app_name = 'users '
urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='users/login.html',
        redirect_authenticated_user=True), name="login"),
    url(r'^logout/$', logout, name="logout"),
]

fossevents/base/models.py
# -*- coding: utf-8 -*-

import uuid

from django.db import models


class UUIDModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class TimeStampedUUIDModel(UUIDModel):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields with UUID as primary_key field.
    """
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True

fossevents/events/models.py
# -*- coding: utf-8 -*-
import uuid

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.functional import cached_property
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django_markdown.models import MarkdownField
from django_markdown.utils import markdown

from fossevents.base.models import TimeStampedUUIDModel
from fossevents.base.utils import get_date_diff_display


class Event(TimeStampedUUIDModel):
    """ Model to capture all details about the event.
    """
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name=_("name"),)
    description = MarkdownField(blank=False, null=False, verbose_name=_("description"))
    start_date = models.DateTimeField(blank=False, verbose_name=_("start date"))
    end_date = models.DateTimeField(blank=True, verbose_name=_("end date"))
    homepage = models.URLField(blank=True, verbose_name=_("homepage"))
    is_published = models.BooleanField(blank=False, null=False, default=False, verbose_name=_("is published"))

    auth_token = models.CharField(blank=True, null=False, max_length=50)
    owner_email = models.EmailField(
        blank=False, null=False, max_length=256, verbose_name=_("owner's email address"),
        help_text=_("An email with the edit link for this event would be sent to this address. \
            Please provide a vaild address here."))

    class Meta:
        verbose_name = _("event")
        verbose_name_plural = _("events")
        ordering = ('-start_date', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'slug': self.slug, 'pk': self.id.hex})

    def get_edit_url(self):
        return reverse('events:update', kwargs={'slug': self.slug, 'pk': self.id.hex, 'token': self.auth_token})

    @property
    def slug(self):
        return slugify(self.name)

    # TODO: return date in localize timezone
    def date(self):
        return get_date_diff_display(self.start_date, self.end_date)

    @cached_property
    def description_html(self):
        return markdown(self.description)

    def save(self, *args, **kwargs):
        if not self.auth_token:
            self.auth_token = str(uuid.uuid4())
        super(Event, self).save(*args, **kwargs)


class EventReview(TimeStampedUUIDModel):
    event = models.ForeignKey(Event, related_name="reviews", on_delete=models.CASCADE)
    comment = MarkdownField(blank=True, null=True, verbose_name=_("Notes"))
    moderator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="event_reviews", on_delete=models.CASCADE)
    is_approved = models.BooleanField()

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return '{} -> {}'.format(self.moderator, self.event)

fossevents/users/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class UserQuerySet(models.QuerySet):
    def moderators(self):
        return self.filter(is_moderator=True)

    def email_users(self):
        return self.filter(is_moderator=True, is_superuser=True, is_staff=True)


class CustomUserManager(UserManager):
    def get_queryset(self):
        return UserQuerySet(self.model, using=self._db)

    def moderators(self):
        return self.get_queryset().moderators()

    def email_users(self):
        return self.get_queryset().email_users()


class User(AbstractUser):

    is_moderator = models.BooleanField('active', default=False,
                                       help_text='Designates whether this user is a moderator or not')

    objects = CustomUserManager()

    def __str__(self):
        return self.username

fossevents/events/forms.py
from django import forms

from .models import Event, EventReview


class EventForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter description...'},),
                                  help_text='<a href="https://guides.github.com/features/mastering-markdown/">'
                                            'Markdown supported</a>')
    start_date = forms.DateTimeField(input_formats=["%Y-%m-%d", "%Y-%m-%d %H:%M"],
                                     widget=forms.DateTimeInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM',
                                                                       'type': 'datetime'},
                                                                format='%Y-%m-%d %H:%M'))
    end_date = forms.DateTimeField(input_formats=["%Y-%m-%d", "%Y-%m-%d %H:%M"],
                                   widget=forms.DateTimeInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM',
                                                                     'type': 'datetime'},
                                                              format='%Y-%m-%d %H:%M'))
    homepage = forms.URLField(widget=forms.URLInput(attrs={'placeholder': 'http://example.com', 'type': 'text'}))

    class Meta:
        model = Event
        exclude = ('auth_token', 'is_published')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Title'}),
            'owner_email': forms.EmailInput(attrs={'placeholder': 'user@example.com'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        if end_date and start_date:
            if end_date < start_date:
                self.add_error('end_date',
                               forms.ValidationError('End date should be greater than or equal to start date.'))
        return cleaned_data


class EventReviewForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter notes or comments...', 'rows': 2},),
                              help_text='<a href="https://guides.github.com/features/mastering-markdown/">'
                                        'Markdown supported</a>',
                              required=False)

    class Meta:
        model = EventReview
        exclude = ('event', 'moderator')
        widgets = {'is_approved': forms.HiddenInput()}

    def clean(self):
        cleaned_data = super().clean()
        is_approved = cleaned_data.get('is_approved')
        comment = cleaned_data.get('comment')
        if not is_approved and not comment:
            self.add_error('comment', forms.ValidationError('Reject reason is required.'))
        return cleaned_data

fossevents/users/forms.py
# -*- coding: utf-8 -*-


from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

fossevents/events/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.http.response import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render

from . import models
from .decorators import match_token
from .forms import EventForm, EventReviewForm
from . import services


def event_detail(request, pk, slug=None, template_name='events/event_detail.html'):
    event = get_object_or_404(models.Event, pk=pk)
    if event.slug != slug:
        return redirect(event.get_absolute_url())
    ctx = {
        'event': event,
    }
    if not request.user.is_anonymous and request.user.is_moderator:
        ctx['review_url'] = services.get_event_review_url(event)
        ctx['form'] = EventReviewForm()

    return render(request, template_name, ctx)


@user_passes_test(lambda u: u.is_moderator)
@login_required()
@require_http_methods(['POST'])
def event_review(request, pk, token, slug=None, event_detail_template='events/event_detail.html'):
    # TODO: Add reference in email for analytics
    # TODO: Add history of reviews in review page
    event = get_object_or_404(models.Event, pk=pk)
    if event.slug != slug:
        return redirect(event.get_absolute_url())

    form = EventReviewForm(data=request.POST)
    if form.is_valid():
        review = services.create_event_review(request.user, event, form.cleaned_data)
        services.update_event_visibility(review)
        services.send_event_review_mail(review, request.user)
        return HttpResponseRedirect(reverse('home'))

    ctx = {
        'event': event,
        'review_url': services.get_event_review_url(event),
        'form': form
    }
    return render(request, event_detail_template, ctx)


class EventCreateView(CreateView):
    form_class = EventForm
    template_name = 'events/event_form.html'

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        response = super().form_valid(form)
        services.send_confirmation_mail(self.object, False)
        return response


class EventUpdateView(UpdateView):
    form_class = EventForm
    template_name = 'events/event_form.html'
    queryset = models.Event.objects.all()

    @method_decorator(match_token)
    def dispatch(self, request, *args, **kwargs):
        return super(EventUpdateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        response = super().form_valid(form)
        services.send_confirmation_mail(self.object, False)
        return response

fossevents/pages/views.py
# -*- coding: utf-8 -*
from django.shortcuts import render
from fossevents.events import services as event_services
from fossevents.events.models import Event


def homepage(request):
    ctx = {
        'events': event_services.get_public_event_listings()
    }
    return render(request, 'pages/home.html', ctx)


def search(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            events = Event.objects.filter(name__icontains=q)
            return render(request, 'pages/home.html', {'events': events})
    ctx = {
        'events': event_services.get_public_event_listings()
    }
    return render(request, 'pages/home.html', ctx)

fossevents/users/views.py
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.contrib.auth import views as auth_views


def logout(request, *args, **kwargs):
    auth_logout(request)
    return HttpResponseRedirect(reverse('users:login'))

fossevents/views.py
# -*- coding: utf-8 -*
from django.shortcuts import render

from fossevents.events import services as event_services


def homepage(request):
    search_term = request.GET.get('q', None)
    upcoming_events = past_events = list()
    if not search_term:
        upcoming_events, past_events = event_services.get_chronologically_sorted_events()
    ctx = {
        'events': event_services.get_public_event_listings(search_term=search_term) if search_term else [],
        'upcoming_events': upcoming_events,
        'past_events': past_events
    }
    return render(request, 'home.html', ctx)

fossevents/templates/about.html
{% extends "base.html" %}

{% block title %}About • {{ block.super }}{% endblock title %}

{% block content %}
    <h1>About Foss Events</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto delectus, culpa laborum iste perferendis, molestias est reiciendis quo, error eos ipsum dolore, provident eum itaque sunt atque cumque consequatur. Sapiente.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati eius facere voluptates ullam labore minima eligendi sapiente laudantium doloribus. Iure pariatur in, dignissimos recusandae error maiores debitis maxime, mollitia cumque!</p>
{% endblock content %}

fossevents/templates/base.html
{% load compress staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <title>{% block title %}FossEvents{% endblock title %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
      <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
      {% compress css %}
      <link rel="stylesheet" type="text/x-scss" href="{% static 'css/main.scss' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
      {% endcompress %}

      {% block feeds %}
      <link type="application/atom+xml" rel="alternate" title="FOSS events ATOM Feed" href="{% url 'feed-atom' %}">
      <link type="application/rss+xml" rel="alternate" title="FOSS Event's RSS Feed" href="{% url 'feed-rss' %}">
      {% endblock feeds %}
   </head>
   <body class='site {% block body_classes %}{% endblock body_classes %} '>
      <header class="site-header">
         <nav>
            <a class="site-logo" href="{% url 'home' %}"><img class="logo" src="{% static 'images/logo.png' %}" /></a>
            <ul>
               <li><a style="padding:10px;" href="{% url 'events:create' %}">Submit an event</a></li>
               {% if user.is_authenticated %}
               <li class="pull-right"><a style="padding:10px;" href="{% url 'users:logout' %}">Logout</a></li>
               {% endif %}

               <form class="site--search" action="{% url 'home' %}" method="GET">
                   <input type="hidden" name="src" value="typd">
                   <input type="text" placeholder="Search events…" name="q" value="{{ request.GET.q }}" {% if request.GET.q %}autofocus{% endif %}>
               </form>
            </ul>
         </nav>
      </header>
      <main class="site-content">
         {% if messages %}
         {% for message in messages %}
         <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
         {% endfor %}
         {% endif %}
         {% block content %}
         <p>Use this document as a way to quick start any new project.</p>
         {% endblock content %}
      </main>
      <footer class='site-footer'>
         <p>
             &copy; fossevents.in •
             <a href="{% url 'about' %}">About</a> |
             <a href="https://github.com/fossevents">Developers</a> |
             <a href="{% url 'privacy' %}">Privacy</a> |
             <a href="https://github.com/fossevents/fossevents.in/issues">Report an issue</a>
         </p>
      </footer>
      {% block modal %}{% endblock modal %}
      <!-- Le javascript
         ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
      {% endblock javascript %}
      {% block extra_javascript %}{% endblock extra_javascript %}
      {% if debug %}<script>{% include "devrecargar/devrecargar.js" %}</script>{% endif %}
   </body>
</html>

fossevents/templates/detail.html
<html>
   <head>
      <link href="../static/css/style.css" rel="stylesheet">
      <link href="../static/css/bootstrap.min.css" rel="stylesheet">
   </head>
   <body>
      <div id="container">
         <div class="navbar navbar-default nav-md">
            <div class="container-fluid">
               <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#"><img src="../static/images/logo.png" style="height:35px;width:70px;"/></a>
               </div>
               <!-- Collect the nav links, forms, and other content for toggling -->
               <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                     <li class="active" style="padding-top:7px;"><a href="#">Submit an Event</a></li>
                  </ul>
               </div>
               <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
         </div>
         <div class="col-md-offset-3 col-md-6">
            <div class="inner">
               <div class="panel panel-default">
                  <div class="panel-heading">
                     <div class="info">
                        <h2 class="title">PYCON India 2015</h2>
                        <span class="desc">April 23rd,9am-6pm(Mon)</span>
                        <p class="desc">23,Nimhans,Bangalore-190001</p>
                     </div>
                     <div class="info">
                        <span >Contact Person:Saurabh Kumar</span>
                        <p>
                           <a href="#"><i class="fa fa-envelope-o "></i></a>&nbsp;
                           <a href="#"><i class="fa fa-share "></i></a>&nbsp;
                           <a href="#"><i class="fa fa-mobile "></i></a>&nbsp;
                        </p>
                     </div>
                  </div>
                  <div class="panel-body">
                     <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida hendrerit rhoncus. 
                        Suspendisse dignissim sagittis nibh ut sagittis. Fusce eu bibendum metus. 
                        Phasellus pellentesque nec lectus non volutpat. 
                        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In tortor urna, tincidunt ac sagittis vitae, pulvinar sit amet nunc. Sed metus dolor, feugiat vitae sapien non, semper ultricies odio. 
                        Mauris interdum lacus non enim pretium, ac accumsan augue scelerisque.
                     </p>
                     <p>
                     <h4>Topic</h4>
                     <ul>
                        <li>Mauris interdum lacus non enim pretium, ac accumsan augue scelerisque.</li>
                        <li>Mauris interdum lacus non enim pretium, ac accumsan augue scelerisque.</li>
                        <li>Mauris interdum lacus non enim pretium, ac accumsan augue scelerisque.</li>
                     </ul>
                     </p>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida hendrerit rhoncus. 
                        Suspendisse dignissim sagittis nibh ut sagittis. Fusce eu bibendum metus. 
                     </p>
                     Suspendisse dignissim sagittis nibh ut sagittis. Fusce eu bibendum metus. </p>
                  </div>
               </div>
            </div>
         </div>
         <div id="footer">
            <div class="container-fluid">
               <p class="navbar-text pull-left">&copy 2015 - FossEvents.in
               </p>
               <p class="navbar-text pull-right">
                  | <a href="#">About</a> 
                  |  <a href="#">Developers</a>
                  |  <a href="#">Privacy</a>
                  |  <a href="#">Report an abuse</a>
               </p>
            </div>
         </div>
      </div>
   </body>
</html>

fossevents/templates/home.html
{% extends "base.html" %}
{% load to_domain from strings %}
{% block body_classes %}{{block.super}} page--home {% endblock body_classes %}
{% block content %}
{% if events %}
    <div class="event--list">
        {% for event in events %}
        <a class="event card-panel" href="{{ event.get_absolute_url }}">
            <h2 class='event--header'>{{ event.name }}</h2>
            <p class="event--date"> {{ event.date }} </p>
            <p class="event--url"> {{ event.homepage|to_domain }} </p>
        </a>
        {% endfor %}
    </div>
{% else %}
    {% if upcoming_events %}
        <div class="event-list-header">
            <h3>Upcoming Events</h3>
        </div>
        <div class="event--list">
            {% for event in upcoming_events %}
            <a class="event card-panel" href="{{ event.get_absolute_url }}">
                <h2 class='event--header'>{{ event.name }}</h2>
                <p class="event--date"> {{ event.date }} </p>
                <p class="event--url"> {{ event.homepage|to_domain }} </p>
            </a>
            {% endfor %}
        </div>
    {% endif %}
    {% if past_events %}
        <div class="event-list-header">
            <h3>Past Events</h3>
        </div>
        <div class="event--list">
            {% for event in past_events %}
            <a class="event card-panel" href="{{ event.get_absolute_url }}">
                <h2 class='event--header'>{{ event.name }}</h2>
                <p class="event--date"> {{ event.date }} </p>
                <p class="event--url"> {{ event.homepage|to_domain }} </p>
            </a>
            {% endfor %}
        </div>
    {% endif %}
{% endif %}
{% endblock content %}

fossevents/templates/privacy.html
{% extends "base.html" %}

{% block title %}Privacy • {{ block.super }}{% endblock title %}

{% block content %}

<h1> Privacy Policy </h1>

<p> Your privacy is important to Fossevents.in.  This privacy statement provides information about the personal information that Fossevents.in collects, and the ways in which Fossevents.in uses that personal information. </p>

<h2> Credit </h2>

<p>This document was created using a Contractology template available at   <a href="http://www.freenetlaw.com">Freenetlaw.com</a>. </p>

<h2>  Personal information collection </h2>

<p>Fossevents.in may collect and use the following kinds of personal information:</p>

<p>
[information about your use of this website (including personal email id);] <br>
[information that you provide using for the purpose of registering with the website (including name and email address);]<br>
[any other information that you post on the website.] <br>
</p>

<p> <b>  Using personal information  </b> </p>

[Fossevents.in] may use your personal information to:
<br>
[administer this website;] <br>
[personalize the website for you;] <br>
[enable your access to and use of the website services;] <br>
[publish information about you on the website;] <br>

<p>Where [Fossevents.in] discloses your personal information to its agents or sub-contractors for these purposes, the agent or sub-contractor in question will be obligated to use that personal information in accordance with the terms of this privacy statement. </p>

<p>In addition to the disclosures reasonably necessary for the purposes identified elsewhere above, [Fossevents.in] may disclose your personal information to the extent that it is required to do so by law, in connection with any legal proceedings or prospective legal proceedings, and in order to establish, exercise or defend its legal rights. </p>

<h2> Securing your data </h2>

<p>[Fossevents.in] will take reasonable technical and organisational precautions to prevent the loss, misuse or alteration of your personal information.</p>

<p>[Fossevents.in] will store all the personal information you provide [on its secure servers].</p>

<h2>Cross-border data transfers</h2>

<p>Information that [Fossevents.in] collects may be stored and processed in and transferred between any of the countries in which [Fossevents.in] operates to enable the use of the information in accordance with this privacy policy.</p>

<p>[In addition, personal information that you submit for publication on the website will be published on the internet and may be available around the world.]</p>

<p>You agree to such cross-border transfers of personal information.</p>

<h2>Updating this statement</h2>

<p>[Fossevents.in] may update this privacy policy by posting a new version on this website.</p>
<p>You should check this page occasionally to ensure you are familiar with any changes.</p>

<h2>Other websites</h2>

<p>This website contains links to other websites.</p>

<p>[Fossevents.in] is not responsible for the privacy policies or practices of any third party.</p>

<h2>Contact [Fossevents.in]</h2>

<p>If you have any questions about this privacy policy or [NAME'S] treatment of your personal information, please write by email to [contact@fossevents.in].</p>

<p>You must retain the "Credit" section in this document. If you wish to use the document without the "Credit" section (e.g. to project a more professional image) then you can get a license to do so <a href="http://www.contractology.com/precedents/freenetlaw-license-privacy-statement.html">  here </a> </p>

<p>It is an infringement of our copyright to use the document without the "Credit" section and without paying the license fee.</p>

{% endblock %}