config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^privacy/$', TemplateView.as_view(template_name='pages/privacy.html'), name="privacy"),

    # Django Admin (Comment the next line to disable the admin)
    url(r'^admin/', include(admin.site.urls)),

    # User management
    # url(r'^users/', include("fossevents.users.urls", namespace="users")),
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fossevents/events/urls.py
# Third Party Stuff
from django.conf.urls import url

from .views import EventCreateView, EventUpdateView, event_review

uuid_regex = '[a-fA-F0-9]{8}-?[a-fA-F0-9]{4}-?[1345][a-fA-F0-9]{3}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{12}'

app_name = 'events'
urlpatterns = [
    url(r'^add/$', EventCreateView.as_view(), name="create"),
    url(r'^update/(?P<slug>[-\w]+)-(?P<pk>%s)-(?P<token>%s)/$' % (uuid_regex, uuid_regex),
        EventUpdateView.as_view(), name="update"),
    url(r'^review/(?P<slug>[-\w]+)-(?P<pk>%s)-(?P<token>%s)/$' % (uuid_regex, uuid_regex),
        event_review, name="review"),
]

fossevents/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from .events.feeds import AtomLatestEventFeed, LatestEvents
from .events.views import event_detail
from .views import homepage

uuid_regex = '[a-fA-F0-9]{8}-?[a-fA-F0-9]{4}-?[1345][a-fA-F0-9]{3}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{12}'

urlpatterns = [
    url(r'^$', homepage, name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
    url(r'^privacy/$', TemplateView.as_view(template_name='privacy.html'), name="privacy"),
    url(r'^(?P<slug>[-\w]+)-(?P<pk>%s)/$' % uuid_regex, event_detail, name="event-detail"),
    url(r'^event/', include('fossevents.events.urls', namespace='events')),
    url(r'^users/', include('fossevents.users.urls', namespace='users')),
]

urlpatterns += [
    url(r'^feed/rss\.xml$', LatestEvents(), name='feed-rss'),
    url(r'^feed/atom\.xml$', AtomLatestEventFeed(), name='feed-atom'),
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^markdown/', include('django_markdown.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^devrecargar/', include(('devrecargar.urls', 'devrecargar'),
                        namespace='devrecargar'))]
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

fossevents/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import logout

app_name = 'users '
urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='users/login.html',
        redirect_authenticated_user=True), name="login"),
    url(r'^logout/$', logout, name="logout"),
]

fossevents/base/models.py
# -*- coding: utf-8 -*-

import uuid

from django.db import models


class UUIDModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class TimeStampedUUIDModel(UUIDModel):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields with UUID as primary_key field.
    """
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True

fossevents/events/models.py
# -*- coding: utf-8 -*-
import uuid

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.functional import cached_property
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django_markdown.models import MarkdownField
from django_markdown.utils import markdown

from fossevents.base.models import TimeStampedUUIDModel
from fossevents.base.utils import get_date_diff_display


class Event(TimeStampedUUIDModel):
    """ Model to capture all details about the event.
    """
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name=_("name"),)
    description = MarkdownField(blank=False, null=False, verbose_name=_("description"))
    start_date = models.DateTimeField(blank=False, verbose_name=_("start date"))
    end_date = models.DateTimeField(blank=True, verbose_name=_("end date"))
    homepage = models.URLField(blank=True, verbose_name=_("homepage"))
    is_published = models.BooleanField(blank=False, null=False, default=False, verbose_name=_("is published"))

    auth_token = models.CharField(blank=True, null=False, max_length=50)
    owner_email = models.EmailField(
        blank=False, null=False, max_length=256, verbose_name=_("owner's email address"),
        help_text=_("An email with the edit link for this event would be sent to this address. \
            Please provide a vaild address here."))

    class Meta:
        verbose_name = _("event")
        verbose_name_plural = _("events")
        ordering = ('-start_date', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'slug': self.slug, 'pk': self.id.hex})

    def get_edit_url(self):
        return reverse('events:update', kwargs={'slug': self.slug, 'pk': self.id.hex, 'token': self.auth_token})

    @property
    def slug(self):
        return slugify(self.name)

    # TODO: return date in localize timezone
    def date(self):
        return get_date_diff_display(self.start_date, self.end_date)

    @cached_property
    def description_html(self):
        return markdown(self.description)

    def save(self, *args, **kwargs):
        if not self.auth_token:
            self.auth_token = str(uuid.uuid4())
        super(Event, self).save(*args, **kwargs)


class EventReview(TimeStampedUUIDModel):
    event = models.ForeignKey(Event, related_name="reviews", on_delete=models.CASCADE)
    comment = MarkdownField(blank=True, null=True, verbose_name=_("Notes"))
    moderator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="event_reviews", on_delete=models.CASCADE)
    is_approved = models.BooleanField()

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return '{} -> {}'.format(self.moderator, self.event)

fossevents/users/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class UserQuerySet(models.QuerySet):
    def moderators(self):
        return self.filter(is_moderator=True)

    def email_users(self):
        return self.filter(is_moderator=True, is_superuser=True, is_staff=True)


class CustomUserManager(UserManager):
    def get_queryset(self):
        return UserQuerySet(self.model, using=self._db)

    def moderators(self):
        return self.get_queryset().moderators()

    def email_users(self):
        return self.get_queryset().email_users()


class User(AbstractUser):

    is_moderator = models.BooleanField('active', default=False,
                                       help_text='Designates whether this user is a moderator or not')

    objects = CustomUserManager()

    def __str__(self):
        return self.username

fossevents/events/forms.py
from django import forms

from .models import Event, EventReview


class EventForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter description...'},),
                                  help_text='<a href="https://guides.github.com/features/mastering-markdown/">'
                                            'Markdown supported</a>')
    start_date = forms.DateTimeField(input_formats=["%Y-%m-%d", "%Y-%m-%d %H:%M"],
                                     widget=forms.DateTimeInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM',
                                                                       'type': 'datetime'},
                                                                format='%Y-%m-%d %H:%M'))
    end_date = forms.DateTimeField(input_formats=["%Y-%m-%d", "%Y-%m-%d %H:%M"],
                                   widget=forms.DateTimeInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM',
                                                                     'type': 'datetime'},
                                                              format='%Y-%m-%d %H:%M'))
    homepage = forms.URLField(widget=forms.URLInput(attrs={'placeholder': 'http://example.com', 'type': 'text'}))

    class Meta:
        model = Event
        exclude = ('auth_token', 'is_published')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Title'}),
            'owner_email': forms.EmailInput(attrs={'placeholder': 'user@example.com'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        if end_date and start_date:
            if end_date < start_date:
                self.add_error('end_date',
                               forms.ValidationError('End date should be greater than or equal to start date.'))
        return cleaned_data


class EventReviewForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter notes or comments...', 'rows': 2},),
                              help_text='<a href="https://guides.github.com/features/mastering-markdown/">'
                                        'Markdown supported</a>',
                              required=False)

    class Meta:
        model = EventReview
        exclude = ('event', 'moderator')
        widgets = {'is_approved': forms.HiddenInput()}

    def clean(self):
        cleaned_data = super().clean()
        is_approved = cleaned_data.get('is_approved')
        comment = cleaned_data.get('comment')
        if not is_approved and not comment:
            self.add_error('comment', forms.ValidationError('Reject reason is required.'))
        return cleaned_data

fossevents/users/forms.py
# -*- coding: utf-8 -*-


from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

fossevents/events/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.http.response import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render

from . import models
from .decorators import match_token
from .forms import EventForm, EventReviewForm
from . import services


def event_detail(request, pk, slug=None, template_name='events/event_detail.html'):
    event = get_object_or_404(models.Event, pk=pk)
    if event.slug != slug:
        return redirect(event.get_absolute_url())
    ctx = {
        'event': event,
    }
    if not request.user.is_anonymous and request.user.is_moderator:
        ctx['review_url'] = services.get_event_review_url(event)
        ctx['form'] = EventReviewForm()

    return render(request, template_name, ctx)


@user_passes_test(lambda u: u.is_moderator)
@login_required()
@require_http_methods(['POST'])
def event_review(request, pk, token, slug=None, event_detail_template='events/event_detail.html'):
    # TODO: Add reference in email for analytics
    # TODO: Add history of reviews in review page
    event = get_object_or_404(models.Event, pk=pk)
    if event.slug != slug:
        return redirect(event.get_absolute_url())

    form = EventReviewForm(data=request.POST)
    if form.is_valid():
        review = services.create_event_review(request.user, event, form.cleaned_data)
        services.update_event_visibility(review)
        services.send_event_review_mail(review, request.user)
        return HttpResponseRedirect(reverse('home'))

    ctx = {
        'event': event,
        'review_url': services.get_event_review_url(event),
        'form': form
    }
    return render(request, event_detail_template, ctx)


class EventCreateView(CreateView):
    form_class = EventForm
    template_name = 'events/event_form.html'

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        response = super().form_valid(form)
        services.send_confirmation_mail(self.object, False)
        return response


class EventUpdateView(UpdateView):
    form_class = EventForm
    template_name = 'events/event_form.html'
    queryset = models.Event.objects.all()

    @method_decorator(match_token)
    def dispatch(self, request, *args, **kwargs):
        return super(EventUpdateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        response = super().form_valid(form)
        services.send_confirmation_mail(self.object, False)
        return response

fossevents/pages/views.py
# -*- coding: utf-8 -*
from django.shortcuts import render
from fossevents.events import services as event_services
from fossevents.events.models import Event


def homepage(request):
    ctx = {
        'events': event_services.get_public_event_listings()
    }
    return render(request, 'pages/home.html', ctx)


def search(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            events = Event.objects.filter(name__icontains=q)
            return render(request, 'pages/home.html', {'events': events})
    ctx = {
        'events': event_services.get_public_event_listings()
    }
    return render(request, 'pages/home.html', ctx)

fossevents/users/views.py
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.contrib.auth import views as auth_views


def logout(request, *args, **kwargs):
    auth_logout(request)
    return HttpResponseRedirect(reverse('users:login'))

fossevents/views.py
# -*- coding: utf-8 -*
from django.shortcuts import render

from fossevents.events import services as event_services


def homepage(request):
    search_term = request.GET.get('q', None)
    upcoming_events = past_events = list()
    if not search_term:
        upcoming_events, past_events = event_services.get_chronologically_sorted_events()
    ctx = {
        'events': event_services.get_public_event_listings(search_term=search_term) if search_term else [],
        'upcoming_events': upcoming_events,
        'past_events': past_events
    }
    return render(request, 'home.html', ctx)

fossevents/templates/events/event_create.html
{% extends "base.html" %}
{% load compress staticfiles %}
{% block body_classes %}{{block.super}}page--event-create{% endblock body_classes %}
{% block title %}Create Event • {{block.super}}{% endblock title %}
{% block content %}
<div class="">
    <form action="" method="post" enctype="multipart/form-data" class="form form--generic form--event-add card-panel">
        {% csrf_token %}
        {% for field in form %}
        <div class="form--input-field">
            {{ field }} {{ field.label_tag }}
            {{ field.errors }}
            {% if field.help_text %}
            <span class="helptext">{{ field.help_text|safe }}</span>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="form-button waves-effect waves-light">Save</button>
    </form>
</div>
{% endblock content %}

fossevents/templates/events/event_detail.html
{% extends "base.html" %}
{% block body_classes %}{{block.super}}page--event-detail{% endblock body_classes %}
{% block title %}{{ event.name }} • {{block.super}}{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
{% if user.is_moderator %}
<div class="event card-panel">
    <form action="{{ review_url }}" method="post" class="form form--generic form--event-add" id="review_form">
        {% csrf_token %}
        <div>
            {% for field in form.hidden_fields %}
            <div class="form--input-field">
                {{ field }}
            </div>
            {% endfor %}
            {% for field in form.visible_fields %}
            <div class="form--input-field">
                {{ field }} {{ field.label_tag }}
                {{ field.errors }}
            </div>
            {% endfor %}
        </div>
        <!--<button type="submit" class="waves-effect waves-light">Reject</button>-->
        <button id="approve_button" class="waves-effect waves-light">Approve</button>
        <button id="reject_button" class="waves-effect waves-light">Reject</button>
    </form>
</div>
{% endif %}
{% endif %}
<div class="event card-panel" role='main'>
   <article>
      <header class="event-head">
         <h1 class="event-title">{{ event.name }}</h1>
         <p class="event-dates">{{ event.date }}</p>
         <p class="event-itemdesc">
            <a href="{{ event.homepage }}" target="blank" rel="nofollow">{{ event.homepage|cut:"http://"|cut:"https://" }}</a>
         </p>
      </header>
      <hr class="simple">
      <div class="event--content">
            {{ event.description_html }}
      </div>
   </article>
   <hr class='accented'>
</div>
{% endblock content %}
{% block extra_javascript %}
    {% if user.is_authenticated %}
        {% if user.is_moderator %}
            <script type="text/javascript">
            $( document ).ready(function() {
                $("#approve_button").click(function() {
                    $("#id_is_approved").val(true);
                    $("#review_form").submit();
                });
                $("#reject_button").click(function() {
                    console.log("Testing");
                    $("#id_is_approved").val(false);
                    $("#review_form").submit();
                });
            });
            </script>
        {% endif %}
    {% endif %}
{% endblock extra_javascript %}

fossevents/templates/events/event_form.html
{% extends "base.html" %}
{% load compress staticfiles %}
{% block body_classes %}{{block.super}}page--event-create{% endblock body_classes %}
{% block title %}Create Event • {{block.super}}{% endblock title %}
{% block content %}
<div class="">
    <form action="" method="post" enctype="multipart/form-data" class="form form--generic form--event-add card-panel">
        {% csrf_token %}
        {% for field in form %}
        <div class="form--input-field">
            {{ field }} {{ field.label_tag }}
            {{ field.errors }}
            {% if field.help_text %}
            <span class="helptext">{{ field.help_text|safe }}</span>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="form-button waves-effect waves-light">Save</button>
    </form>
</div>
{% endblock content %}